version: '3.5'
services:
  db:
    image: postgres:latest
    volumes:
      - ecam_db_pgdata:/var/lib/postgresql/data
      - ~/Downloads/homeCreditData/to_db:/home/jovyan/ecam_ds/data/input
    ports: 
      - "5432:5432"
    container_name: container_ecam_db
    networks:
      - custom_network
networks:
  custom_network:
    name: ecam_db_network
volumes:
  ecam_db_pgdata:
