version: '2'
services:
  db:
    image: postgres:latest
    volumes:
      - ecam_db_pgdata:/var/lib/postgresql/data
      - ~/Downloads/homeCreditData/to_db:/home/jovyan/ecam_ds/data/input
    ports: 
      - "5432:5432"
    container_name: container_ecam_db
volumes:
  ecam_db_pgdata:
