FROM postgres:latest

#COPY requirements.cfg requirements.cfg
#RUN pip install --upgrade pip
#RUN pip install -r requirements.cfg
#RUN jupyter contrib nbextensions install --sys-prefix --skip-running-check
