version: '3.5'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/jovyan/
      - ~/Coding/repos/:/home/jovyan/repos_link
      - ~/Desktop/:/home/jovyan/Desktop_link
    ports:
      - "8888:8888"
    container_name: container_ecam_ds
    networks:
      - custom_network
networks:
  custom_network:
    name: ecam_ds_network
